root: true

env:
    node: true

extends: "eslint"

rules:
    no-undefined: 0
    require-jsdoc: 0
    space-before-function-paren: [2, {"anonymous": "always", "named": "never"}]
    spaced-comment: [0, "always", { exceptions: ["-"]}]
